// Copyright 2024 Joey Innes <joey@inneslabs.uk>

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: can.proto

package can

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Can struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dats [][]byte `protobuf:"bytes,1,rep,name=dats,proto3" json:"dats,omitempty"`
}

func (x *Can) Reset() {
	*x = Can{}
	if protoimpl.UnsafeEnabled {
		mi := &file_can_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Can) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Can) ProtoMessage() {}

func (x *Can) ProtoReflect() protoreflect.Message {
	mi := &file_can_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Can.ProtoReflect.Descriptor instead.
func (*Can) Descriptor() ([]byte, []int) {
	return file_can_proto_rawDescGZIP(), []int{0}
}

func (x *Can) GetDats() [][]byte {
	if x != nil {
		return x.Dats
	}
	return nil
}

var File_can_proto protoreflect.FileDescriptor

var file_can_proto_rawDesc = []byte{
	0x0a, 0x09, 0x63, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x19, 0x0a, 0x03, 0x43,
	0x61, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x73, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x63, 0x61, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_can_proto_rawDescOnce sync.Once
	file_can_proto_rawDescData = file_can_proto_rawDesc
)

func file_can_proto_rawDescGZIP() []byte {
	file_can_proto_rawDescOnce.Do(func() {
		file_can_proto_rawDescData = protoimpl.X.CompressGZIP(file_can_proto_rawDescData)
	})
	return file_can_proto_rawDescData
}

var file_can_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_can_proto_goTypes = []interface{}{
	(*Can)(nil), // 0: Can
}
var file_can_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_can_proto_init() }
func file_can_proto_init() {
	if File_can_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_can_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Can); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_can_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_can_proto_goTypes,
		DependencyIndexes: file_can_proto_depIdxs,
		MessageInfos:      file_can_proto_msgTypes,
	}.Build()
	File_can_proto = out.File
	file_can_proto_rawDesc = nil
	file_can_proto_goTypes = nil
	file_can_proto_depIdxs = nil
}
